<?php 
  get_header(); // this is a word press built in functio that just gets ur header 
  require get_template_directory() . '/inc/section_vars.php';
?>
<!-- 
<h1>The Front Page</h1>

<?php if (get_theme_mod($home_top_img)) // if this customized image exists, then throw the image in. this allows clients to upload and change their home page's top iamge { ?>
  <img 
    src="<?php echo get_theme_mod($home_top_img) ?>" 
    alt=""
  >
<?php?>

<?php if (get_theme_mod($home_top_desc)) // if the top description exists then go ahead and put description on the page  { ?>
  // get_theme_mod essentially gets whatever is in the related thing on the wordpress admin site and ur code puts that stuff on the website 
  <h4>
    <?php echo get_theme_mod($home_top_desc) ?>
  </h4>
<?php?>

// Example with default video if $home_top_vid isn't set
<iframe 
  class="yt-vid" 
  src="<?php echo get_theme_mod($home_top_vid, 'https://www.youtube.com/embed/A0Wyx-OOX4A'); ?>" 
  frameborder="0" 
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>

 -->

<div id="header-container"> 
  
  <div id="picture-container"> 
    <img src="<?php echo get_template_directory_uri(); ?>/images/profile-pic.png"/> 
  </div> 

  <div id="greeting-container">
    <p id="greeting-line">Hi, I'm Celina Pan
    </p>
    <div class="header-paragraph"> I’m a sophomore at the University of Michigan studying comptuer science and data science. My interests lie in software enginnering, data science, and data engineering.
    </div>
  </div>  
  
  
</div>

<div id="about-me-container"> 
  <label class="about-me-header"> 
    <h2>About Me</h2>
  </label>

  <label class="about-me-body">
    <p> I am currently a sophomore at the University of Michigan with an intended dual major in comptuer science and data science. I have more than five years of coding programming experience, and am especially  interested in machine learning, AI, and NLP. I come from Taipei, Taiwan, and in my down time, I enjoy reading, writing, and going on nature adventures. 
    </p>
  </label>
  
</div>

<div id="skills-bar">
  <label class = "python"> 
    <h3> Python </h3>
    <p> 5+ years of experience <br> 4 years of formal education <br> Experience with multiple data science and machine learning libraries </p>
  </label>

  <label class = "cplusplus"> 
    <h3> C++ </h3>
    <p> 2+ years of experience <br> 2+ years of formal education <br> Experience with many algorithms and data structures </p>
  </label>

  <label class = "html-css"> 
    <h3> HTML/CSS </h3>
    <p> 1 month of experience <br> 1 month of education <br> Learning basic web site development skills </p>
  </label>

</div>

<div id="projects-container">
  <h2>Projects <br> </h2>
  <div class = "stock-project">
    <h3>Stock Prediction Project</h3>
    <p> For this personal project, I used multiple Python libraries including sys, pandas, Matplotlib, NumPy, scikit-learn, and Beautiful Soup to create a program capable of predicting the future stock prices of a user inputted stock using a linear regression model trained on historical closing price data parsed form Yahoo Finance. <br> I also used PyQt5 to create an interactive and intuitive GUI interface that takes in user input and outputs relevant stock data and predicted stock prices in an easily comprehendible manner. <br> <br></p>
  </div>
  <div class = "classifier-project">
    <h3>Classifer Project</h3>
    <p> For this class project, my partner and I collaboratively programmed a classifier that uses natural language processing and machine learning techniques to classify the subject of student posts on an educational questions forum using past student post data, resulting in experience with recursion, binary trees, templates, comparators, and the map data structure for both of us. Together, we conducted the unit testing and debugging of the final classifier, which resulted in a program that passed all coding style requirements and 46/47 instructor test cases. </p>
  </div>
</div>

<div id="experience-container">
  <h2>Experience</h2>
  <div class = "gic">
    <h3>Global Investments Committee</h3>
    <p> As a portfolio manager for this student club, I collaborated with a team of 4 to analyze data generated by risk management software and conducted market research to provide our club with insights on how to optimize our portfolio to reduce risk and increase profits. This led to the purchase of Lockheed Martin (NYSE: LMT) stock, the sale of Weibo (NASDAQ: WB) stock, and other actions that resulted in the portfolio generating 20% returns in a period of 4 months.  <br> 

    Furthermore, I also contributed to a final deliverable of stock pitch on the Israeli crop protection company, ADAMA (SHE: 000553), by conducting 5 stock screenings and 15+ hours of industry research in team of 6 on the Global Equities Desk. In my role as an analyst, I synthesized relevant information and delivered final results to club of 50+ members. 
    <br> <br>
    </p>
  </div>
  <div class = "theta">
    <h3>Theta Capital</h3>
    <p> In this student club, I performed qualitative analysis on the Taiwan Semiconductor Manufacturing Company’s (NYSE: TSM) financial data, delivering a stock pitch in a club-wide pitch competition with over 30 participants and tying for first place, which resulted in the purchase of $1425 worth of TSM stock for our paper portfolio. <br> In addition to this, I also produced 5 detailed stock reports on international companies across travel, technology, and energy industries by analyzing company financials, management, and operations as well as those of competitors, leading to a prioritized list of stocks used in decision-making by club members for club and personal investments. 
    <br> <br>
    </p>
  </div>
  <div class = "speech">
    <h3>Speech and Debate</h3>
    <p> I have competed in multiple forms of speech and debate for six years, resulting in exceptional communication, research, public speaking, debating, and critical thinking skills, even under immense pressure. At my best, I placed third at the 2019 ROC National Speech and Debate Tournament in international extemporaneous speaking, hence qualifying to participate and compete in the 2019 US National Speech and Debate Tournament. Through this experience, I gained a deeper understanding of global issues and further developed my public speaking and research skills. </p>
  </div>
</div>



 

<?php get_footer(); ?>
